### PR TITLE
Add GenServer-like child_spec definitions.

### PR DESCRIPTION
**Pull request by archSeer**
I kinda 1:1 copied the definitions out of GenServer, but it's a start.

### CODE REVIEW

**Comment by archSeer** [comment]
Using it would look like so:

```elixir
children = [
  {MyPublisher, [
        Hare.Conn,
        [exchange: [name: "my_exchange", opts: [durable: true]]],
        [name: App.Publisher]
  ]}
]

opts = [strategy: :one_for_one, name: App.Supervisor]
Supervisor.start_link(children, opts)

```

**Comment by take-five** [comment]
@archSeer hmm, Travis cannot build that on Elixir 1.4

**Comment by archSeer** [comment]
Sorry about that! It needed the `bind_quoted: [opts: opts]`. This rebuild should fix it.

**Comment by take-five** [comment]
So how do you use it with new `opts`? Could you please write a small usage example in the `@moduledoc` section of both modules?

**Comment by take-five** [comment]
Or maybe just mention that it works with Elixir 1.5 childspecs

**Comment by willmore** [comment]
@archSeer are you able to make the requested changes by @take-five?

**Comment by take-five** [comment]
No feedback given, closing

**Pull request closed without merging**
